name: Tests

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: true
      matrix:
        php: [8.1, 8.2, 8.3]
        laravel: [9.*, 10.*, 11.*]
        dependency-version: [prefer-lowest, prefer-stable]
        exclude:
          - laravel: 11.*
            php: 8.1

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: pcov

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
          if [[ "${{ matrix.laravel }}" == "9.*" ]]; then
            composer require "orchestra/testbench:~7.0" --dev --no-interaction --no-update
          elif [[ "${{ matrix.laravel }}" == "10.*" ]]; then
            composer require "orchestra/testbench:~8.0" --dev --no-interaction --no-update
          elif [[ "${{ matrix.laravel }}" == "11.*" ]]; then
            composer require "orchestra/testbench:~9.0" --dev --no-interaction --no-update
          fi
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-plugins

      - name: List Installed Dependencies
        run: composer show -D

      - name: Execute tests
        run: composer test

      - name: Execute PHPStan
        run: composer analyse

      - name: Execute PHP CS Fixer
        run: composer check-format